### ISSUE TITLE
Error computing p-site offsets

### ISSUE THREAD

**Issue by pabloaguirreazorin** [jipingw/RiboDiPA#12]
My experiment consists of six samples divided in two groups. I want to carry out RiboDiPA analysis, but I got an error related with p-site mapping:

`Computing P-site offsets`

`Computing coverage` 
`for/Data/Raw/RiboSeq/IMGN_B17/IMGN_B17_Riboseq_results/Alignment/B17_01/B17_01Aligned.sorted.bam...`
`done!`

`Computing coverage` 
`for/Data/Raw/RiboSeq/IMGN_B17/IMGN_B17_Riboseq_results/Alignment/B17_02/B17_02Aligned.sorted.bam...`
`done!`

`Computing coverage` 
`for/Data/Raw/RiboSeq/IMGN_B17/IMGN_B17_Riboseq_results/Alignment/B17_03/B17_03Aligned.sorted.bam...`
`done!`

`Computing coverage` 
`for/Data/Raw/RiboSeq/IMGN_B17/IMGN_B17_Riboseq_results/Alignment/B17_04/B17_04Aligned.sorted.bam...`

`Error in { :`
`  task 1 failed - "attempt to set index 10/10 in SET_STRING_ELT"`
`Calls: RiboDiPA ... psiteMapping -> .pMappingAll -> %dopar% -> <Anonymous>`
`Execution halted`

I got the same error with another sample. The bam files I used are raw, sorted and indexed before I ran RiboDiPA, and I didn't find any  anomalies such as unmapped reads, duplicates, or improperly formatted reads when I checked BAM statistics with flagstat. I also tried with previous RiboDiPA version 1.08.0 with the same results.

Could you provide me some insights about what it could be happening (if possible), please?

Thanks very much in advance.

Session info:
[1] RiboDiPA_1.10.0 GenomicAlignments_1.38.0
[3] SummarizedExperiment_1.32.0 MatrixGenerics_1.14.0
[5] matrixStats_1.4.1 GenomicFeatures_1.54.1
[7] AnnotationDbi_1.64.1 Biobase_2.62.0
[9] Rsamtools_2.18.0 Biostrings_2.70.1
[11] XVector_0.42.0 GenomicRanges_1.54.1
[13] GenomeInfoDb_1.38.1 IRanges_2.36.0
[15] S4Vectors_0.40.2 BiocGenerics_0.48.1

**Comment by pabloaguirreazorin** [comment]
I have just tried with RiboDiPA version 1.14.0 and the error remains consistent.

Has anyone encountered this issue before or could provide guidance on how to resolve it?

**Comment by jipingw** [comment]
I found the issues is due to the contamination of your sequence reads. In the data you sent to me, for example in B17_04Aligned.sorted.bam, the read #2695907 length is 123 nt instead of 20 nt (see below). Furthermore this read was aligned to genome and the alignment was strange. The 123 nt spans 17 different segment of the genome (see cigar score below), some aligned regions are only of length a few nt.

Typically your read length is 20 bp, and it either spans one exon, or span two exons with intron in between. 

This cause an issue in parsing the cigar string. The length of the segments exceeds the pre-set length of the vector (""attempt to set index 10/10 in SET_STRING_ELT").

> gal3[2695907]
Key: <qwidth>
   qwidth seqnames strand                                                         cigar    start      end width njunc psite
    <int>   <fctr> <fctr>                                                        <char>    <int>    <int> <int> <int> <num>
1:    123        1      - 10M1624N27M1467N9M803N9M1227N6M1943N18M3234N27M3894N9M1983N8M 67634419 67650716 16298     8    12

Solution: 
1. remove such contaminated reads based on the query read length from the bam file. The RiboDiPA does not automatically do that, as the read length may varies from experiments.
2. I will come up with an update of the package soon, allowing longer length of the vector. #1 is the ultimate way to remove the contamination issue. #2 here is a way to avoid the code error for such situations. Since such contamination only accounts for a few reads in the entire data set, it shouldn't be a concern.
